apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: my-kubernetes-app
build:
  artifacts:
  - image: andyheyns93/kub-app
    context: src\angular-app
    docker:
      dockerfile: Dockerfile
  - image: andyheyns93/kub-api
    context: src\dotnet-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/all.deployment.yml
