apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api
  labels:
    app: kubernetes-api
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kubernetes-api
  template:
    metadata:
      labels:
        app: kubernetes-api
    spec:
      containers:
      - name: kubernetes-api
        image: andyheyns93/kub-api:0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-api
  ports:
    - port: 8080
      targetPort: 80